In [ ]:
''' Week 02 Lab: Image Processing Through a Four-Step Pipeline

   Course: Perceptual Computing / Computer Graphics and Human-Computer Interaction



Name: Mohsin Jokhio
Roll number: 2K24/CSE/85
GitHub username:2K24CSE85 '''


In [ ]:
def rgb_to_grayscale(r, g, b):
    # TODO 1: calculate grayscale value
    y = 0.299 * r + 0.587 * g + 0.114 * b

    # TODO 2: round the result
    return round(y)


# Test
print(rgb_to_grayscale(180, 120, 60))


131


In [ ]:
import numpy as np

def adjust_brightness_contrast(image, alpha, beta):
    adjusted = alpha * image + beta
    adjusted = np.clip(adjusted, 0, 255)
    return adjusted.astype(np.uint8)

image = np.array([[100, 150], [200, 50]], dtype=np.uint8)

print(adjust_brightness_contrast(image, 1.5, -20))


[[130 205]
 [255  55]]


In [ ]:
#--->FIVE PROBLEMS START FROM HERE!<---

In [ ]:
import numpy as np

def threshold_image(image, threshold):
    output = np.where(image >= threshold, 255, 0)
    return output.astype(np.uint8)

image = np.array([[20, 128, 200],
                  [100, 150, 250]], dtype=np.uint8)

print(threshold_image(image, 128))


[[  0 255 255]
 [  0 255 255]]


In [ ]:
def image_memory(width, height, bpp):
    total_bits = width * height * bpp
    total_bytes = total_bits // 8
    return total_bytes

print(image_memory(1920, 1080, 24))


: 

In [ ]:
import numpy as np

def average_9_pixels(block):
    total = np.sum(block)
    average = total / 9
    return round(average)

block = np.array([[10, 20, 10],
                  [30, 50, 30],
                  [10, 20, 10]])

print(average_9_pixels(block))


21


In [ ]:
import numpy as np

def change_range(values, old_min, old_max, new_min, new_max):
    new_values = (values - old_min) / (old_max - old_min) * (new_max - new_min) + new_min
    return new_values

values = np.array([50, 100, 150])

print(change_range(values, 50, 150, 0, 255))


[  0.  127.5 255. ]


In [ ]:
import numpy as np

def sobel_edge(block):
    gx_kernel = np.array([[-1, 0, 1],
                          [-2, 0, 2],
                          [-1, 0, 1]])

    gy_kernel = np.array([[-1, -2, -1],
                          [0, 0, 0],
                          [1, 2, 1]])

    gx = np.sum(block * gx_kernel)
    gy = np.sum(block * gy_kernel)

    strength = np.sqrt(gx * gx + gy * gy)
    return gx, gy, strength

block = np.array([[20, 20, 200],
                  [20, 20, 200],
                  [20, 20, 200]])

print(sobel_edge(block))


(np.int64(720), np.int64(0), np.float64(720.0))


In [ ]:
''' THE END '''